### PR TITLE
Widen analyzer range to include v1

### PR DESCRIPTION
**Pull request by evanweible-wf**
This package is compatible with analyzer v1, so this PR widens the range to include it which will help unblock consumers from upgrading to v1.

Other changes:
- Switch from Travis CI to GitHub workflow
- Drop the dart_dev and dart_style dependencies and use `dart` CLI directly for simplicity

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by robbecker-wf — APPROVED** [review]

**Review by greglittlefield-wf — APPROVED** [review]
+10

**Comment by evanweible-wf** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
