### PR TITLE
UIP-1906 Widen version constraints

### PR DESCRIPTION
**Pull request by jacehensley-wf**
## Ultimate Problem
`analyzer` was being bound to <0.28.0, we should widen that constraint to allow <0.30.0.

## Solution
- Widen the `analyzer` version constraint

## Testing Suggestions
- Verify tests still pass

## Possible Areas of Regression
- None expected

---
FYA: @greglittlefield-wf @evanweible-wf

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
Number of Findings: 0

**Comment by greglittlefield-wf** [comment]
+1

**Comment by rm-astro-wf** [comment]
Sorry, I could not create a JIRA ticket for this pull.

I sent the following data to JIRA:
`{'issuetype': {'name': None}, 'project': {'key': u'UIP'}, 'description': '## Ultimate Problem\r\n`analyzer` was being bound to <0.28.0, we should widen that constraint to allow <0.30.0.\r\n\r\n## Solution\r\n- Widen the `analyzer` version constraint\r\n- Remove unnecessary `coverage` dependency\r\n\r\n## Testing Suggestions\r\n- Verify tests still pass\r\n\r\n## Possible Areas of Regression\r\n- None expected\r\n\r\n---\r\nFYA: @greglittlefield-wf @evanweible-wf ', 'components': [], 'summary': 'Widen version constraints, remove unnecessary coverage'}`

I received the following data from JIRA:
`Hidden on Open Source Repos`

If this is an issue that you cannot resolve, please reach out to RM in the Release Management chat room.

**Comment by evanweible-wf** [comment]
+1

**Comment by greglittlefield-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by greglittlefield-wf** [comment]
Waiting on Smithy to be enabled for this repo (ticket # TBA)

**Comment by greglittlefield-wf** [comment]
+1

**Comment by leviwith-wf** [comment]
QA Resource Approval: +10
- smithy is running
- tests are passing

----

- [X] Testing instruction
- [X] Dev +1's
- [X] Dev/QA +10
- [X] All unit tests pass

merging

**Pull request merged**
