### PR TITLE
Null safety

### PR DESCRIPTION
**Pull request by robbecker-wf**
Migrate to null safety.

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
The items listed below may not capture all security relevant changes. Before providing a security review, be sure to review the entire PR for security impact.
<details>
<summary>(1) Security relevant changes were detected</summary>
<li>Watched file <code>lib/src/transformed_source_file.dart</code> modified</li>
</details>

## Action Items
* Obtain a [security review](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); reviewer should pay special attention to insights listed above
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by robbecker-wf** [comment]
QA+1 CI passes 
consumer testing passes @Workiva/release-management-p

**Comment by robbecker-wf** [comment]
security +1

**Comment by corwinsheahan-wf** [comment]
security +1
* Changes just accomodate null safety by allowing null types, which were already allowed. No functional changes in flagged file

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
